### ISSUE TITLE
Duplicate command

### ISSUE THREAD

**Issue by fr34kyn01535** [LeeIzaZombie/RocketMod_ColorChat#1]
Hey LeelzaZombie,
the Built-in /broadcast <message> <color> does the same thing so i didn't publish your plugin.
By the way - you can get a color by name, or by hex color (#eee, #e1e1e1, "black") by using RocketChat.ColorFromName("...");.

Have fun :)

**Comment by LeeIzaZombie** [comment]
Haven't noticed, thanks for the feedback! Definitely gonna help when I add color config to my other plugins!
